FROM node:12-alpine
RUN node -v \
    && npm -v \
    && npm config set registry https://registry.npm.taobao.org \
    && npm config list \
    && npm install -g pm2 \
    && pm2 --version \
    && pm2-runtime --version \
    && pm2-docker --version \
    && pm2-dev --version \


